FROM node:20-alpine AS builder

WORKDIR /app
COPY . .
RUN npm install && npm run build

RUN useradd -m -u 1000 app


FROM nginx:alpine

COPY --from=builder --chown=app:app /app/dist /usr/share/nginx/html

USER app
