services:
  backend:
    restart: "no"

    ports:
      - "8000:8000"

    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/

          ignore:
            - .venv
            - ./backend/.venv

        - action: rebuild
          path: ./backend/pyproject.toml
