services:
  backend:
    restart: no
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/alembic/versions:/app/app/alembic/versions
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
          ignore:
            - .venv
            - ./backend/.venv
        - action: rebuild
          path: ./backend/pyproject.toml
