services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src/backend:/app/src/backend
    environment:
      - UV_COMPILE_BYTECODE=0
    command: fastapi dev --host 0.0.0.0 /app/src/backend
    restart: no
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
          ignore:
            - .venv
            - ./backend/.venv

        - action: rebuild
          path: ./backend/pyproject.toml
