services:
  backend:
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
          ignore:
            - .venv
            - ./backend/.venv

        - action: rebuild
          path: ./backend/pyproject.toml
