services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - UV_COMPILE_BYTECODE=0
    command: fastapi dev --host 0.0.0.0 /app/src/backend
    restart: no
    develop:
      watch:
        - action: sync
          path: ./backend/src/backend
          target: /app/src/backend
          ignore:
            - .venv
            - ./backend/.venv

        - action: rebuild
          path: ./backend/pyproject.toml
