services:
  backend:
    restart: no
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src/backend:/app/src/backend
      # - ./backend/.venv:/app/.venv
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
          ignore:
            - .venv
            - ./backend/.venv
        - action: rebuild
          path: ./backend/pyproject.toml
