services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    command: uvicorn app.src.backend:app --host 0.0.0.0 --port 8000 --reload
    develop:
      watch:
        - action: sync
          path: ./backend/src/backend
          target: /app/src/backend
          ignore:
            - .venv
            - ./backend/.venv
        - action: rebuild
          path: ./backend/pyproject.toml
